name: abriefescape
favicon: null
layout_spectrum: 0.9561932298820466
typography_spectrum: 0.1810756225604564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7891375329345465
  lightness: 0.9471492145676166
  saturation: 0.21538203745149076
  rhythmicContrast: 0.5224495455622673
purpose: []
